version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: pets-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petsdb
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
